# Data Source properties
---
spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost}:${DB_PORT:5432}/${DB_NAME:atm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    initialization-mode: always
    initialize: true
    schema: classpath:/db/V2.0__initialize_db.sql
    continue-on-error: true


# JPA properties
---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

