# Data Source properties
---
spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost}:${DB_PORT:5432}/${DB_NAME:atm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

# JPA properties
---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        format_sql: true